-- MySQL Script generated by MySQL Workbench
-- sob, 13 kwi 2019, 15:09:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema linie_lotnicze
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema linie_lotnicze
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `linie_lotnicze` DEFAULT CHARACTER SET utf8 ;
USE `linie_lotnicze` ;

-- -----------------------------------------------------
-- Table `linie_lotnicze`.`przewoziciele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linie_lotnicze`.`przewoziciele` (
  `nazwa_firmy` VARCHAR(15) NOT NULL,
  `kraj` VARCHAR(20) NOT NULL,
  `data_zalozenia` DATE NOT NULL,
  `budzet` INT NULL,
  PRIMARY KEY (`nazwa_firmy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linie_lotnicze`.`loty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linie_lotnicze`.`loty` (
  `nazwa_lotu` VARCHAR(10) NOT NULL,
  `koszt` INT NOT NULL,
  `data` DATE NOT NULL,
  `czas_min` INT NOT NULL,
  `ilosc_km` INT NOT NULL,
  `start` VARCHAR(20) NOT NULL,
  `cel` VARCHAR(20) NOT NULL,
  `typ` VARCHAR(15) NOT NULL,
  `img` VARCHAR(25) NOT NULL,
  `przewoziciele_nazwa_firmy` VARCHAR(15) NULL,
  PRIMARY KEY (`nazwa_lotu`),
  INDEX `fk_loty_przewoziciele1_idx` (`przewoziciele_nazwa_firmy` ASC),
  CONSTRAINT `fk_loty_przewoziciele1`
    FOREIGN KEY (`przewoziciele_nazwa_firmy`)
    REFERENCES `linie_lotnicze`.`przewoziciele` (`nazwa_firmy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linie_lotnicze`.`piloci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linie_lotnicze`.`piloci` (
  `id_pilota` INT NOT NULL,
  `imie` VARCHAR(15) NOT NULL,
  `nazwisko` VARCHAR(15) NOT NULL,
  `data_zatrudnienia` DATE NOT NULL,
  `pensja` INT(11) NOT NULL,
  `ilosc_lotow` INT NOT NULL,
  `przewoziciele_nazwa_firmy` VARCHAR(15) NULL,
  PRIMARY KEY (`id_pilota`),
  UNIQUE INDEX `id_pilota_UNIQUE` (`id_pilota` ASC),
  INDEX `fk_piloci_przewoziciele1_idx` (`przewoziciele_nazwa_firmy` ASC),
  CONSTRAINT `fk_piloci_przewoziciele1`
    FOREIGN KEY (`przewoziciele_nazwa_firmy`)
    REFERENCES `linie_lotnicze`.`przewoziciele` (`nazwa_firmy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linie_lotnicze`.`karty_klientow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linie_lotnicze`.`karty_klientow` (
  `numer` INT NOT NULL AUTO_INCREMENT,
  `stan_konta` INT(11) NOT NULL,
  `data_waznosci` DATE NOT NULL,
  `ilosc_transakcji` INT(11) NOT NULL,
  PRIMARY KEY (`numer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linie_lotnicze`.`uzytkownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linie_lotnicze`.`uzytkownicy` (
  `login` VARCHAR(20) NOT NULL,
  `haslo` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(35) NOT NULL,
  `imie` VARCHAR(20) NOT NULL,
  `nazwisko` VARCHAR(20) NOT NULL,
  `nr_tel` INT(9) NOT NULL,
  `data_rejestracji` INT(10) NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  `prestiz` INT(3) NOT NULL DEFAULT 0,
  `pytanie_pom` VARCHAR(20) NOT NULL,
  `karty_klientow_numer` INT NULL,
  INDEX `fk_uzytkownicy_karty_klientow_idx` (`karty_klientow_numer` ASC),
  PRIMARY KEY (`login`),
  CONSTRAINT `fk_uzytkownicy_karty_klientow`
    FOREIGN KEY (`karty_klientow_numer`)
    REFERENCES `linie_lotnicze`.`karty_klientow` (`numer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp850;


-- -----------------------------------------------------
-- Table `linie_lotnicze`.`opinie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linie_lotnicze`.`opinie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tresc` VARCHAR(60) NOT NULL DEFAULT 'Jestem zadowolonym klientem! :)',
  `ocena` INT(1) NOT NULL DEFAULT 5,
  `nick` VARCHAR(20) NOT NULL,
  `loty_nazwa_lotu` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_opinie_loty1_idx` (`loty_nazwa_lotu` ASC),
  CONSTRAINT `fk_opinie_loty1`
    FOREIGN KEY (`loty_nazwa_lotu`)
    REFERENCES `linie_lotnicze`.`loty` (`nazwa_lotu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linie_lotnicze`.`samoloty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linie_lotnicze`.`samoloty` (
  `numer_seryjny` INT NOT NULL,
  `producent` VARCHAR(20) NOT NULL,
  `model` VARCHAR(20) NOT NULL,
  `rok_produkcji` INT NOT NULL,
  `ilosc_miejsc` INT NOT NULL,
  `ilosc_lotow` INT NOT NULL,
  `przewoziciel` VARCHAR(15) NULL,
  PRIMARY KEY (`numer_seryjny`),
  INDEX `fk_samoloty_przewoziciele1_idx` (`przewoziciel` ASC),
  CONSTRAINT `fk_samoloty_przewoziciele1`
    FOREIGN KEY (`przewoziciel`)
    REFERENCES `linie_lotnicze`.`przewoziciele` (`nazwa_firmy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linie_lotnicze`.`hotele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linie_lotnicze`.`hotele` (
  `id_hotelu` VARCHAR(5) NOT NULL,
  `nazwa_hotelu` VARCHAR(25) NOT NULL,
  `miasto` VARCHAR(20) NOT NULL,
  `gwiazdki` INT NOT NULL,
  `ilosc_miejsc` INT NOT NULL,
  `cena_za_dobe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_hotelu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linie_lotnicze`.`destynacje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linie_lotnicze`.`destynacje` (
  `id_lotniska` VARCHAR(3) NOT NULL,
  `nazwa_lotniska` VARCHAR(45) NOT NULL,
  `miasto` VARCHAR(20) NOT NULL,
  `kraj` VARCHAR(45) NOT NULL,
  `hotele_id_hotelu` VARCHAR(5) NULL,
  `loty_nazwa_lotu` VARCHAR(10) NULL,
  INDEX `fk_destynacje_hotele1_idx` (`hotele_id_hotelu` ASC),
  PRIMARY KEY (`id_lotniska`),
  INDEX `fk_destynacje_loty1_idx` (`loty_nazwa_lotu` ASC),
  CONSTRAINT `fk_destynacje_hotele1`
    FOREIGN KEY (`hotele_id_hotelu`)
    REFERENCES `linie_lotnicze`.`hotele` (`id_hotelu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_destynacje_loty1`
    FOREIGN KEY (`loty_nazwa_lotu`)
    REFERENCES `linie_lotnicze`.`loty` (`nazwa_lotu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
